services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password


  telegraf:
    image: telegraf:latest
    container_name: telegraf
    user: root
    command: >
      sh -c "chmod 666 /var/run/docker.sock || true && telegraf"
    depends_on:
      - influxdb
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - influxdb

  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    depends_on:
      - influxdb
    volumes:
      - ./config/grafana-provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana-provisioning/dashboards:/var/lib/grafana/dashboards
      - ./config/grafana-provisioning/dashboards-config:/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=testdb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  elasticsearch:
    image: elasticsearch:8.10.4
    container_name: elasticsearch
    environment:
      - ingest.geoip.downloader.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elasticsearch_data:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  app:
    image: marynakovalova/hsa13-hw2-app:latest
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/testdb?authSource=admin
      - ELASTICSEARCH_HOST=elasticsearch
    depends_on:
      - mongodb
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 30s
