apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: telegraf
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: password
    isDefault: true